name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  file-path:
    description: 'Path to the file'
    required: true
  app-info:
    description: 'Apps list'
    required: true
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'