name: 'Updates server file (specific feature)'
description: 'Updates server file with recently added json keys'
inputs:
  endpoint:
    description: 'Endpoint'
    required: true
  query-params:
    description: 'Query params'
    required: false
  file-path:
    description: 'Path to the file'
    required: true
  backup-file-path:
    description: 'Backup file path'
    required: true
  current-branch:
    description: 'Branch name'
    required: true
  app-info:
    description: 'Apps list'
    required: true
    
runs:
  using: 'node16'
  main: 'index.js'