name: 'Updates server file (specific feature)'
description: 'Updates server file with recently added json keys'
inputs:
  endpoint:
    description: 'Endpoint'
    required: true
  file-path:
    description: 'Path to the file'
    required: true
  backup-file-path:
    description: 'Backup file path'
    required: true
  current-branch:
    description: 'Branch name'
    required: true
  secrets-context:
    description: 'Secrets context'
    required: true
  secret-suffix:
    description: 'Secret suffix to identify the one that will be used'
    required: true
    
runs:
  using: 'node16'
  main: 'index.js'