name: 'Sync with server'
description: 'Syncing files with server'
inputs:
  endpoint:
    description: 'Endpoint'
    required: true
  query-params:
    description: 'Query params'
    required: false
  file-path:
    description: 'Path to the file'
    required: true
  backup-file-path:
    description: 'Backup file path'
    required: true
  current-branch:
    descrption: 'Branch name'
    required: true
  app-info:
    description: 'Apps list'
    required: true
outputs:
  downloaded-json-file:
    description: 'Json file to be saved'
    
runs:
  using: 'node16'
  main: 'index.js'