name: 'Sync with server'
description: 'Syncing translations with server'
inputs:
  owner:
    description: 'Repo owner'
    required: true
  repo:
    description: 'Repository containing the json file to update'
    required: true
  current-branch:
    description: 'Current branch'
    required: true
  file-path:
    description: 'Path to the file'
    required: true
  app-info:
    description: 'Apps list'
    required: true
  token:
    description: 'token'
    required: true
outputs:
  downloaded-json-file:
    description: 'Json file to be saved'
    
runs:
  using: 'node16'
  main: 'index.js'