name: 'Update json files and create a pull request'
description: 'Updates current json files and creates a pull request'
inputs:
  owner:
    description: 'Repo owner'
    required: true
  repo:
    description: 'Repository containing the json file to update'
    required: true
  file-path:
    description: 'Path to the file'
    required: true
  secrets-context:
    description: 'Secrets context'
    required: true
  token:
    description: 'Token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'