name: 'Update translations and create a pull request'
description: 'Updates current translations and creates a pull request'
inputs:
  file-path:
    description: 'Path to the file'
    required: true
  app-info:
    description: 'Apps list'
    required: true
  token:
    description: 'token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'